version: '3.9'

services:
  # backend-service
#  spring-boot-observability:
#    build:
#      context: . # Use the current directory as the build context
#      dockerfile: Dockerfile # Specify the Dockerfile to use
#    container_name: spring-boot-observability-container
#    restart: always
#    ports:
#      - "8080:8080" # Expose Spring Boot on port 8080
#    depends_on:
#      - tempo
#      - loki
#      - prometheus
#    networks:
#      - app_network

  # Prometheus Service
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    command:
      - --enable-feature=exemplar-storage
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/prometheus-data:/prometheus
    networks:
      - app_network
      - observability

  ## Tempo Service
  tempo:
    image: grafana/tempo
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "3200:3200" # Tempo
      - "9411:9411" # zipkin
    networks:
      - app_network
      - observability

  #loki Service
  loki:
    image: grafana/loki:main
    container_name: loki
    command: [ "-config.file=/etc/loki/loki-config.yaml" ]
    ports:
      - "3100:3100"
    volumes:
      - ./docker/loki/loki-data:/loki
      - ./docker/loki/config:/etc/loki
    networks:
      - app_network
      - observability

  # Grafana Service
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - app_network
      - observability

networks:
  app_network: # Custom network for container communication
    driver: bridge
  observability:
    external: true