global:
  scrape_interval: 2s
  evaluation_interval: 2s
scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['backend:8080']
        labels:
          application: 'Helping Hands Backend'